baseURL = "http://stacked-git.github.io/"
languageCode = "en-us"
title = "Stacked Git"
theme = ""

[params]
description = "Manage stack of Git commits"
logoimage = "stgit.svg"

[menu]
  [[menu.main]]
    name = "Changelog"
    url = "/changelog/"
    weight = -100
  [[menu.main]]
    name = "Man Pages"
    url = "/man/"
    weight = -99
  [[menu.main]]
    name = "Guides"
    url = "/guides/"
    weight = -98
  [[menu.main]]
    name = "Tutorial"
    url = "/guides/tutorial/"
    weight = -97
  [[menu.main]]
    name = "Repository"
    url = "https://github.com/stacked-git/stgit/"
    post = '<img src="/github.svg" alt="GitHub logo">'
    weight = -89
  [[menu.main]]
    name = "Issue Tracker"
    url = "https://github.com/stacked-git/stgit/issues"
    post = '<img src="/github.svg" alt="GitHub logo">'
    weight = -87
  [[menu.main]]
    name = "Releases"
    url = "https://github.com/stacked-git/stgit/releases"
    post = '<img src="/github.svg" alt="GitHub logo">'
    weight = -86
  [[menu.main]]
    name = "Forum"
    url = "https://groups.google.com/d/forum/stgit"
    post = '<img src="/ext-link.svg" alt="external link">'
    weight = -79


[markup]
  [markup.highlight]
    noclasses = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
